# Generated by Django 4.2.4 on 2023-11-22 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_alter_depositproducts_dcls_end_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='like_users',
            field=models.ManyToManyField(related_name='like_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
